OPENAI_API_KEY = "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"
PDFCROWD_USERNAME = "dein_username"
PDFCROWD_API_KEY = "dein_api_key"
